<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="32435" started-at="2020-10-13T11:20:31Z" finished-at="2020-10-13T11:21:04Z">
    <groups>
    </groups>
    <test name="AppTest" duration-ms="32435" started-at="2020-10-13T11:20:31Z" finished-at="2020-10-13T11:21:04Z">
      <class name="testcases.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.LoginTest@36d585c]" name="setUp" is-config="true" duration-ms="17958" started-at="2020-10-13T11:20:13Z" finished-at="2020-10-13T11:20:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testcases.LoginTest@36d585c]" name="beforeClass" is-config="true" duration-ms="5" started-at="2020-10-13T11:20:31Z" finished-at="2020-10-13T11:20:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="LoginInputs(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:testcases.LoginTest@36d585c]" name="LoginInputs" duration-ms="19057" started-at="2020-10-13T11:20:31Z" data-provider="dp" finished-at="2020-10-13T11:20:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[aktest123.demos.disciple.tools]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[aktest123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2hBIQW4k4Pxm]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginInputs -->
        <test-method status="FAIL" signature="LoginInputs(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:testcases.LoginTest@36d585c]" name="LoginInputs" duration-ms="11390" started-at="2020-10-13T11:20:51Z" data-provider="dp" finished-at="2020-10-13T11:21:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[aktest123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2hBIQW4k4Pxm]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login is NOT succcessful with valid parameters expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login is NOT succcessful with valid parameters expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at testcases.LoginTest.LoginInputs(LoginTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginInputs -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.LoginTest@36d585c]" name="tearDown" is-config="true" duration-ms="3021" started-at="2020-10-13T11:21:04Z" finished-at="2020-10-13T11:21:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.LoginTest -->
    </test> <!-- AppTest -->
  </suite> <!-- Suite -->
</testng-results>
